services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "${ZOOKEEPER_INTERNAL_PORT:-2181}:${ZOOKEEPER_PORT:-2181}"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_INTERNAL_PORT:-2181}
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "${KAFKA_BROKER_INTERNAL_PORT:-9092}:${KAFKA_BROKER_PORT:-9092}"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT:-2181}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_BROKER_PROTOCOL:-PLAINTEXT}://${KAFKA_BROKER_HOST:-localhost}:${KAFKA_BROKER_INTERNAL_PORT:-9092}
      KAFKA_LISTENERS: ${KAFKA_BROKER_PROTOCOL:-PLAINTEXT}://0.0.0.0:${KAFKA_BROKER_INTERNAL_PORT:-9092}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "${REDIS_INTERNAL_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  postgres:
    image: postgres:18.1-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
    - "${DB_INTERNAL_PORT:-5432}:${DB_PORT:-5432}"
    volumes:
    - postgres_data:/var/lib/postgresql

volumes:
  redis_data:
    name: dundie_awards_redis_data
  postgres_data:
    driver: local