springdoc:
  api-docs:
    path: /openapi
server:
  port: 3000

spring:
    # datasource:
    #   url: jdbc:h2:mem:mydb
    #   username: sa
    #   password: password
    #   driverClassName: org.h2.Driver
    # jpa:
    #   spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin123
  jpa:
    show-sql: true
    properties:
      ## Hibernate Properties
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update

  thymeleaf: # Thymeleaf
    cache: false
    mode: HTMLs
    encoding: UTF-8
    prefix: file:src/main/resources/static/

  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0

  redis:
    host: localhost

  cloud:
    stream:
      bindings:
        activity-out-0:
          destination: activity
          content-type: application/json
        activity-in-0:
          destination: activity
          group: activity-consumer-group
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
          # health-timeout: 30
          # autoCreateTopics: false
        bindings:
          activity-in-0:
            consumer:
              ackMode: MANUAL
              maxAttempts: 3
              backOffInitialInterval: 2000
              enableDlq: true
              dlqName: activity-dlq
   
